In [1]:
## 1. Write a function to compute 5/0 and use try/except to catch the exceptions.
try:
    x = 5 / 0
except:
    print("Undefined when dividing by zero")

Undefined when dividing by zero


In [3]:
## 2. Implement a Python program to generate all sentences where subject is in 
# ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

'''
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
Output should come as below:
Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.
'''

subjects = ["Americans", "Indians"]
verbs = ["Play", "watch"]
objects = ["Baseball","cricket"]

sentence_list = [(sub+" "+ vb + " " + ob) for sub in subjects for vb in verbs for ob in objects]
for sentence in sentence_list:
    print(sentence)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


In [8]:
'''
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.
'''

import numpy as np
a = np.array ([1,2,4,6])
N=4
np.vander(a, N)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 64,  16,   4,   1],
       [216,  36,   6,   1]])

In [9]:
np.column_stack([a**(N-1-i) for i in range(N)])

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 64,  16,   4,   1],
       [216,  36,   6,   1]], dtype=int32)

In [10]:
np.vander(a, increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   4,  16,  64],
       [  1,   6,  36, 216]])

In [11]:
np.vander(a, increasing=False)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 64,  16,   4,   1],
       [216,  36,   6,   1]])